config/routes.rb
Company::Application.routes.draw do

  resources :photos, :only => [:index, :show, :new, :create] do
    post 'upload', :on => :collection
  end

  match "/albums" => "albums#index"
  match "/social_post" => "home#social_post"
  post "users/unique_email"
  get "home/" => "home#index"
  get "home/lookup_address" =>"home#lookup_address"
  get 'home/autocomplete'
  get 'home/autocomplete_category'
  get 'home/get_current_position' => 'home#get_current_position' ,:as => :get_current_position
  get 'offers/tmp_list' , :as => :offers_list
  get "/users/get_user"
  get '/list_offers' => "offers#list_offer" , :as => :list_offers
  get 'merchats/tmp_detail'
  get 'offers/tmp_filter'
  get '/categories/top_lvl'
  get '/merchants/get_offers_quota'
  match 'categories/:category' => "categories#category"
  match 'categories/:category/offers' => "categories#offers"
  match 'categories/:category/:sub_category' => "categories#sub_category"
  match 'categories/:category/:sub_category/offers' => "categories#offers"
  
  resources :articles
  resources :countries do
    resources :cities
  end

  
  match '/users/profile' => 'users#show' ,:as => :user_profile
  match '/merchants/get_image' => 'merchants#get_image' ,:as => :merchant_get_image
  match '/offers/get_image' => 'offers#get_image' ,:as => :offer_get_image

  match "offers/:id/get_images" => "offers#get_image"
  post 'offers/create/:id'  => "offers#create"
  
  match "/images/:id/delete" => "images#destroy" ,:as => :delete_image
  match "/merchant_images/:id/delete" => "merchant_images#destroy" ,:as => :delete_merchant_image
  match "/offer_images/:id/delete" => "offer_images#destroy" ,:as => :delete_offer_image
  match 'offers/new' => 'offers#new'
  match '/offers' => 'offers#index'
  get 'offers/create/:id'  => "offers#get_offer"

  devise_for :users, :controllers => { :registrations => "registrations",:omniauth_callbacks => "omniauth_callbacks",:sessions => "sessions" }
  match "/offers/get_more_offers" => "offers#get_more_offers"
  
  resources :merchant_types
  resources :merchants do
    collection do
      get 'set_favourite'
    end
    resources :offers do 
      collection do
        get 'set_favourite'
      end
    end
  end

  match '/users/profile/users/update' =>  'users#update'
  match '/users/update' =>  'users#update'
  match '/users/friends' => 'users#friends'
  match '/users/find_friend_oauth_provider' => 'users#find_friend_oauth_provider'
  match '/users/friend_action' => 'users#friend_action'
  match '/users/invite' => 'users#invite'

  match '/chats/find/:id' => 'chats#find'
  match '/chats/load_more' => 'chats#load_more'
  match '/chats/init' => 'chats#init'
  match '/chats/add_recent_chat' => 'chats#add_recent_chat'

  post '/get_google_places'  => "offers#get_google_places"

  
  root :to =>'home#index'

end

app/views/shared/_form_login.erb
<div class="menu_login_container rfloat">
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
    <table cellspacing="0">
      <tbody>
      <tr>
        <td class="html7magic">
          <label for="email">Email or User name</label>
        </td>
        <td class="html7magic">
          <label for="pass">Password</label>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.email_field :email, :class => 'inputtext' %>
        </td>
        <td>
          <%= f.password_field :password, :class => 'inputpassword' %>
        </td>
        <td>
            <%= f.submit t("users.sign_in.submit"), :class => "btn btn-success btn_sign_in" %>
        </td>
      </tr>
      <tr>
        <td class="login_form_label_field">

            <%- if devise_mapping.rememberable? %>

                <label for="persist_box" class="keep_me_login"><%= f.check_box :remember_me, :checked => true, :class => "checkbox_keep_me_login" %>Keep me logged in</label>
            <% end %>
        </td>
        <td class="login_form_label_field">
          <%= link_to t("users.public.forgot_your_password"), new_password_path(resource_name),:class => "forgot_your_password" %>
        </td>
      </tr>
      </tbody>
    </table>
<% end %>
</div>

app/views/shared/_form_logout.html.erb
<%- if user_signed_in? %>
  <a href="<%= user_profile_path  %> "><%=  current_user.email %></a>
  <%= link_to t("users.public.sign_out"), destroy_user_session_path, :method => "delete" %>
<% end %>

app/views/shared/_links_mobile.erb
<ul data-role="listview" data-inset="true" style="margin-top: 20px;margin-bottom: 20px;border-radius:10px;">
<%- if controller_name != 'sessions' %>
  <li><%= link_to t("users.public.sign_in"), new_session_path(resource_name) %></li>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <li><%= link_to t("users.public.sign_up"), new_registration_path(resource_name) %></li>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <li><%= link_to t("users.public.lost_password"), new_password_path(resource_name) %></li>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <li><%= link_to t("users.public.receive_confirmation_instructions"), new_confirmation_path(resource_name) %></li>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <li><%= link_to t("users.public.receive_unlock_instructions"), new_unlock_path(resource_name) %></li>
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
  <li><%= link_to "#{t('users.public.sign_in_with')+' '+ provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider),:rel => "external" %></li>
  <% end -%>
<% end -%>
</ul>

app/views/shared/_menu_top.html.erb
<div class="subnav">
  <div style="margin: 0 auto">
    <ul class="nav nav-pills">
      <li class="active"><%= link_to 'Offers', offers_list_path %></li>
      <li class=""><%=  link_to 'Countries' , countries_path %></li>
      <li><a href="/auth/google_oauth2"> Google contact</a></li>
      <li><input type="button" value="Google contact" id="find_friend_google" class="btn"> </input></li>
      <li><a href="contacts/find_friend_google" class="btn"> Google contact</a></li>

    </ul>
  </div>
</div>

app/views/shared/_nav_home.mobile.erb
<div  data-type="horizontal" data-role="controlgroup" style="text-align: center;">
  <%= link_to t("home.index.home"), root_path,"data-role" =>"button", "data-theme" =>"c"  %>
  <%= link_to t("offers.index.offers_list"),list_offers_path,  "data-role" =>"button", "data-theme" =>"c" %>
</div>

app/views/shared/_session_user.mobile.erb
<%- if user_signed_in? %>
   <a href="<%= user_profile_path  %> "> <%= t("namespace.user")+': ' + current_user.email %></a>&nbsp;&nbsp;&nbsp;&nbsp;
   <%= link_to t("users.public.sign_out"), destroy_user_session_path, :method => "delete" %>
<% end %>