config/routes.rb
Company::Application.routes.draw do

  resources :photos, :only => [:index, :show, :new, :create] do
    post 'upload', :on => :collection
  end

  match "/albums" => "albums#index"
  match "/social_post" => "home#social_post"
  post "users/unique_email"
  get "home/" => "home#index"
  get "home/lookup_address" =>"home#lookup_address"
  get 'home/autocomplete'
  get 'home/autocomplete_category'
  get 'home/get_current_position' => 'home#get_current_position' ,:as => :get_current_position
  get 'offers/tmp_list' , :as => :offers_list
  get "/users/get_user"
  get '/list_offers' => "offers#list_offer" , :as => :list_offers
  get 'merchats/tmp_detail'
  get 'offers/tmp_filter'
  get '/categories/top_lvl'
  get '/merchants/get_offers_quota'
  match 'categories/:category' => "categories#category"
  match 'categories/:category/offers' => "categories#offers"
  match 'categories/:category/:sub_category' => "categories#sub_category"
  match 'categories/:category/:sub_category/offers' => "categories#offers"
  
  resources :articles
  resources :countries do
    resources :cities
  end

  
  match '/users/profile' => 'users#show' ,:as => :user_profile
  match '/merchants/get_image' => 'merchants#get_image' ,:as => :merchant_get_image
  match '/offers/get_image' => 'offers#get_image' ,:as => :offer_get_image

  match "offers/:id/get_images" => "offers#get_image"
  post 'offers/create/:id'  => "offers#create"
  
  match "/images/:id/delete" => "images#destroy" ,:as => :delete_image
  match "/merchant_images/:id/delete" => "merchant_images#destroy" ,:as => :delete_merchant_image
  match "/offer_images/:id/delete" => "offer_images#destroy" ,:as => :delete_offer_image
  match 'offers/new' => 'offers#new'
  match '/offers' => 'offers#index'
  get 'offers/create/:id'  => "offers#get_offer"

  devise_for :users, :controllers => { :registrations => "registrations",:omniauth_callbacks => "omniauth_callbacks",:sessions => "sessions" }
  match "/offers/get_more_offers" => "offers#get_more_offers"
  
  resources :merchant_types
  resources :merchants do
    collection do
      get 'set_favourite'
    end
    resources :offers do 
      collection do
        get 'set_favourite'
      end
    end
  end

  match '/users/profile/users/update' =>  'users#update'
  match '/users/update' =>  'users#update'
  match '/users/friends' => 'users#friends'
  match '/users/find_friend_oauth_provider' => 'users#find_friend_oauth_provider'
  match '/users/friend_action' => 'users#friend_action'
  match '/users/invite' => 'users#invite'

  match '/chats/find/:id' => 'chats#find'
  match '/chats/load_more' => 'chats#load_more'
  match '/chats/init' => 'chats#init'
  match '/chats/add_recent_chat' => 'chats#add_recent_chat'

  post '/get_google_places'  => "offers#get_google_places"

  
  root :to =>'home#index'

end

app/models/offer.rb
require 'active_support'
require 'mongoid'

class Offer
  include Mongoid::Document
  include Geocoder::Model::Mongoid

  #  geocoded_by :primary_address
  #  after_validation :geocode

  embeds_many :images , as: :imageable
  #embedded_in :merchant
  #embedded_in :merchant_test

  embeds_many :addresses, as: :locatable
  # belongs_to :city
   belongs_to :merchant
  # belongs_to :user

  # temporary
  field :status,:type => String
  #field :merchant_id,    :type => String



  # field :coordinates, :type => Array

  # field :city_id,    :type => String
  # field :user_id,    :type => String
  field :merchant_id,    :type => String
  field :name,    :type => String
  field :active,    :type => Integer
  field :description,    :type => String
  # field :primary_address,    :type => String
  field :start_time,    :type => Time
  field :end_time,    :type => Time
  field :category_id, :type => String
  field :category_name , :type => String
  field :price,    :type => Float#
  field :value,    :type => Float#
  field :discount,    :type => Float#
  field :link,    :type => String
  # field :image,    :type => String
  # field :image_thumbnail,    :type => String
  #  field :lon,    :type => Float
  #  field :lat,    :type => Float
  field :currency,    :type => String
  field :timezone,    :type => String
  # field :city_name,    :type => String
  # field :day_in_week,    :type => Integer

  embeds_many :day_in_weeks
  field :favourite_count,:type => Integer
  field :favourite_voters ,    :type => Array # tags contain voter




  # gem geocoder
  include Geocoder::Model::Mongoid
  geocoded_by :add_description     # select field use to generate coordinates[lng,lat]
  after_validation :geocode

  field :coordinates, :type => Array
  field :add_description, type: String
  field :phone , type: String
  field :mobile_phone , type: String

  field :created_at,    :type => DateTime, :default => DateTime.current
  field :updated_at,    :type => DateTime, :default => DateTime.current
  field :mon, :type => Boolean
  field :tue, :type => Boolean
  field :wed, :type => Boolean
  field :thu, :type => Boolean
  field :fri, :type => Boolean
  field :sat, :type => Boolean
  field :sun, :type => Boolean
  field :local_mon_start_time, :type => DateTime
  field :utc_mon_start_time, :type => DateTime
  field :local_mon_end_time, :type => DateTime
  field :utc_mon_end_time, :type => DateTime

  field :local_tue_start_time, :type => DateTime
  field :utc_tue_start_time, :type => DateTime
  field :local_tue_end_time, :type => DateTime
  field :utc_tue_end_time, :type => DateTime

  field :local_wed_start_time, :type => DateTime
  field :utc_wed_start_time, :type => DateTime
  field :local_wed_end_time, :type => DateTime
  field :utc_wed_end_time, :type => DateTime

  field :local_thu_start_time, :type => DateTime
  field :utc_thu_start_time, :type => DateTime
  field :local_thu_end_time, :type => DateTime
  field :utc_thu_end_time, :type => DateTime

  field :local_fri_start_time, :type => DateTime
  field :utc_fri_start_time, :type => DateTime
  field :local_fri_end_time, :type => DateTime
  field :utc_fri_end_time, :type => DateTime

  field :local_sat_start_time, :type => DateTime
  field :utc_sat_start_time, :type => DateTime
  field :local_sat_end_time, :type => DateTime
  field :utc_sat_end_time, :type => DateTime

  field :local_sun_start_time, :type => DateTime
  field :utc_sun_start_time, :type => DateTime
  field :local_sun_end_time, :type => DateTime
  field :utc_sun_end_time, :type => DateTime
  field :status_quota, :type => Boolean
  #validation
  #validates_presence_of :name
  validates_presence_of :description
  #validates_presence_of :value
  #validates_presence_of :price
  #validates_presence_of :category_id





end

app/controllers/offers_controller.rb
require "simple_time_select"
class OffersController < ApplicationController
  #  load_and_authorize_resource
  include Geocoder::Model::Mongoid
  include ApplicationHelper
  LIMIT_OFFER = 5

  def set_favourite # Dieu :D
    @merchant = Merchant.find(params[:merchant_id])
    @offer = @merchant.offers.find(params[:id])
    if params[:status].to_i == 0
      @offer.favourite_count +=1
      @offer.favourite_voters += current_user.id.to_s.to_a
      @offer.save
      render :json => 'vote'.to_json
    else
      @offer.favourite_count -=1
      @offer.favourite_voters -= current_user.id.to_s.to_a
      @offer.save
      render :json => 'unvote'.to_json
    end
    
  end
    
  def index # Dieu , not finish

    #tam comment lai de chay post offer => Tin
    @offer = Offer.new
    #@categories = Category.where(tags: nil).to_a
    #@categories.collect! {|item| {:label => item.category_languages[0].name, :id =>item._id }}
    #city_name = City.find(cookies['city_id']).name.to_a
    #if session[:lon]
    #  puts '111111111111111111111111111111111111'
    #  puts session[:lat] + ', ' + session[:lon]
    #  @arr_merchant = Merchant.near([ session[:lat].to_f , session[:lon].to_f ], 10000).order("distance").map(& :offers)
    #  @offers =  get_offer(@arr_merchant,LIMIT_OFFER)
    #else
    #  puts '2222222222222222222222222222'
    #  @arr_merchant = Merchant.near([request.location.lat,request.location.lng], 10000).order("distance").map(& :offers)
    #  @offers =  get_offer(@arr_merchant,LIMIT_OFFER)
    #end
    
  end

  def new
    @merchant = Merchant.find(params[:merchant_id])
    @offer = @merchant.offers.new
    @offer.day_in_weeks.build
  end

  def show
    @offer = Merchant.find(params[:merchant_id]).offers.find(params[:id])
  end

  def edit
    @offer = Merchant.find(params[:merchant_id]).offers.find(params[:id])
  end

  def create
    @offers=[]
    #    params[:event][:time] = Time.parse(params[:event][:"time(5i)"])
    #    params[:event].delete(:”time(5i)”).


    @merchant = Merchant.find(params[:id])
    @offer = @merchant.offers.new(params[:offer])
    if !params[:files].nil?

        if @offer.save
          params[:files].each do |file|
            @offer.images.create(:url=>  file)
          end
          @offers << @offer
              respond_to do |format|
            format.html { redirect_to '/' }
            format.json { render json: @offers }
          end

        else
          #respond_to do |format|
          #  format.json { render json: @offer.errors }
          #end
          render :text => 'false1'
        end

    else
      render :text => false
    end
  end

  def destroy
    @merchant = Merchant.find(params[:merchant_id])
    @offer = @merchant.offers.find(params[:id])
    @offer.destroy
    redirect_to @merchant
  end

  def update
    @offer = Merchant.find(params[:merchant_id]).offers.find(params[:id])
    @offer.update_attributes(params[:offer])
    redirect_to @offer
  end

  def get_more_offers # Dieu :D
    city_name = City.find(cookies['city_id']).name.to_a
    if params[:offset] == 'undefined' || params[:merchant_offset]== 'undefined'
      render :text => ''
    else
      
      @arr_merchant = Merchant.near([ session[:lat].to_f , session[:lon].to_f ], 10000).order("distance").in(:city_tags=>city_name).map(& :offers)
      @offers =  get_offer(@arr_merchant,params[:offset].to_i,LIMIT_OFFER)
      
      #      @next_offset = params[:offset].to_i + 1
      #      @html_offers = render_to_string :partial => "get_more_offer"
      #      render :json => @html_offers.to_json
      render :json => @offers.to_json
    end
  end


  def get_image  # Dieu :D
    @images = []
    #@merchant = Merchant.find(params[:object_parent_id])
    #@offer = @merchant.offers.find(params[:object_id])
    @offer = Offer.all()
    if !params[:files].nil?
      params[:files].each do |file|
        @images << @offer.images.create(:url=>file)
      end
    end
    if !params[:object_id].nil? && !params[:image].nil?
      @images << @offer.images.create(:url=>params[:image])
    end

    if params[:files].nil?
      @images = @offer.images
    end
    if is_mobile_device?
      #redirect_to merchant_offer_path(@merchant,@offer)

    else
      respond_to do |format|
        format.html # index.html.erbb
        format.json { render json: @images }
      end
    end
    render :text => 'true'
  end

  def list_offer # Dieu :D
    city_name = City.find(cookies['city_id']).name.to_a
    if session[:lon]
      puts '111111111111111111111111111111111111'
      puts session[:lat] + ', ' + session[:lon]
      @arr_merchant = Merchant.near([ session[:lat].to_f , session[:lon].to_f ], 10000).order("distance").in(:city_tags=>city_name).map(& :offers)
      @offers =  get_offer(@arr_merchant,0,LIMIT_OFFER)
    else
      puts '2222222222222222222222222222'
      @arr_merchant = Merchant.near([request.location.lat,request.location.lng], 10000).order("distance").in(:city_tags=>city_name).map(& :offers)
      @offers =  get_offer(@arr_merchant,0,LIMIT_OFFER)
    end
  end

  def get_google_places
    session[:city_id] = 'West New York_United States'
    merchants = Merchant.get_google_places(params[:content], session[:city_id])
    puts merchants
    render :json => merchants
  end

  def get_offer
    @offers = []
    @offers = Offer.where(:merchant_id => params[:id])
    render json: @offers

  end


end

app/helpers/offers_helper.rb
module OffersHelper



end

app/views/offers/_form.html.erb
<%= javascript_include_tag "validate_form.js" %>
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>
      <ul>
        <% @offer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/offers/_form_bk.mobile.erb
<%= javascript_include_tag "validate_form.js" %>
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>
      <ul>
        <% @offer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    <span class="offer_name help-inline"></span>
  </div>

  <div class="control-group">
    <%= f.label :primary_address %>
    <%= f.text_field :primary_address ,:class => 'validate'%>
    <span class="offer_primary_address help-inline"></span>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
    <span class="description help-inline"></span>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
    <span class="offer_price help-inline"></span>
  </div>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
    <span class="offer_value help-inline"></span>
  </div>

  <div class="field">
    <%= f.label :discount %><br />
    <%= f.text_field :discount %>
    <span class="offer_discount help-inline"></span>
  </div>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
    <span class="offer_link help-inline"></span>
  </div>

  <div class="field">
    <%= f.label :currency %><br />
    <%= f.text_field :currency %>
    <span class="offer_currency help-inline"></span>
  </div>

  <div class="field">
    <%= f.label :timezone %><br />
    <%= f.text_field :timezone %>
    <span class="offer_timezone help-inline"></span>
  </div>

  <div class="field">
    <%= f.label :city_name %><br />
    <%= f.text_field :city_name %>
    <span class="offer_city_name help-inline"></span>
  </div>

  <div class="field">
    <%= f.label :day_in_week %><br />
    <%= f.text_field :day_in_week %>
    <span class="offer_day_in_week help-inline"></span>
  </div>

  <div class="actions">
    <%=  f.submit 'Submit', :class=>'btn btn-primary btn-large' %>
  </div>
<% end %>

app/views/offers/_get_more_offer.erb
<% if !@offers.nil? %>
  <% @offers.each_with_index do |offer,offset| %>
    <li class="offer ui-btn ui-btn-icon-right ui-li ui-li-has-alt ui-corner-bottom ui-btn-up-c" data-offset="<%= @next_offset %>" data-theme="c">
      <div class="ui-btn-inner ui-li ui-li-has-alt">
        <div class="ui-btn-text">
          <a class="ui-link-inherit" href="<%= offer_path(offer)%>">
            <h3 class="ui-li-heading"><%=  offer.name %></h3>
            <p class="ui-li-desc"><%=  offer.description %></p>
          </a>
          <div class="ui-corner-all ui-controlgroup ui-controlgroup-horizontal" data-type="horizontal" data-role="controlgroup">
            <%= link_to 'Edit', edit_offer_path(offer) ,'data-role'=>'button' %>
            <a href="#" data-role="none" title="share on facebook"><img class='author-image-button' src="assets/mobile/facebook.png" /></a>
            <a href="#" data-role="none" title="share on twiter"><img class='author-image-button' src="assets/mobile/twitter.png" /></a>
            <a href="#" data-role="none" title="add to google+"><img class='author-image-button' src="assets/mobile/google.png" /></a>
          </div>
        </div>
      </div>
      <a class="ui-li-link-alt ui-btn ui-corner-br ui-btn-up-c" rel="nofollow" data-method="delete" data-icon="delete" data-confirm="Are you sure?" href="/offers/4fa3b4627a03714632000004" title="Destroy" data-theme="c">
        <span class="ui-btn-inner">
          <span class="ui-btn-text"></span>
          <span class="ui-btn ui-btn-up-b ui-btn-icon-notext ui-btn-corner-all ui-shadow" title="" data-theme="b">
            <span class="ui-btn-inner ui-btn-corner-all">
              <span class="ui-btn-text"></span>
              <span class="ui-icon ui-icon-delete ui-icon-shadow"></span>
            </span>
          </span>
        </span>
      </a>
    </li>
    <% @next_offset = @next_offset + 1 %>
  <% end %>
<% end %>

app/views/offers/_sub_category.mobile.erb
<ul class="ui-listview">
<% @sub_categories.each do |sub| %>
  <li class="ui-li ui-li-static ui-body-c">
    <%= sub.name %>
  </li>
<% end %>
</ul>

app/views/offers/index.html_backup.erb
<br />
<div class='span4 offset4' >
  <% if current_user and current_user.merchant == nil %>
    <%= link_to t("offers.index.you_are_merchant"),new_merchant_path %>
  <% elsif current_user and current_user.merchant  %>
    <%= link_to "My Merchant",current_user.merchant %>
  <% end %>
  <% if current_user and current_user.merchant != nil %>
    <%= link_to 'New offer', new_offer_path , 'data-role'=>'button' ,'data-theme'=>'c'%>
  <% end %>
</div>

<br style="clear:both;" />

<ul data-role="listview"  data-inset="true">
  <li data-role="list-divider"  >Offers</li>
  <% unless @offers.empty? %>
    <% @offers.each_with_index do |offer,offset| %>
      <li data-offset="" class="offer">
        <a href="<%= offer_path(offer)%> ">
          <h3><%=  offer.name %></h3>
          <p><%=  offer.description %></p>
        </a>
        <%= link_to 'Destroy', offer, confirm: 'Are you sure?', method: :delete ,'data-icon'=>'delete'%>
        <div data-role="controlgroup" data-type="horizontal">
          <%= link_to 'Edit', edit_offer_path(offer) ,'data-role'=>'button' %>
          <a href="#" data-role="none" title="share on facebook"><img class='author-image-button' src="assets/mobile/facebook.png" /></a>
          <a href="#" data-role="none" title="share on twiter"><img class='author-image-button' src="assets/mobile/twitter.png" /></a>
          <a href="#" data-role="none" title="add to google+"><img class='author-image-button' src="assets/mobile/google.png" /></a>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>
<div id ="lastPostLoader" style="position:static; bottom: 10px; width:100%;height: 40px;">
  <table  style="text-align: center; width: 100%; margin-top: 20px;">
    <tr>
      <td><%= image_tag("bigLoader.gif" , :style=>"width:40px;height:40px;") %></td>
    </tr>
  </table>
</div>

<%= content_for :jsScript do %>
  <script type="text/javascript">
    $(document).ready(function(){
      var flag_scroll = 1;
      $('#lastPostLoader').hide();

      function get_more_when_can_not_scroll()
      {
        flag_scroll = 0;
        if($(document).height()- $(window).height() == 0)
        {
          var offset = $(".offer:last").attr("data-offset");
          $('#lastPostLoader').show();
          $.get("/offers/get_more_offers?offset="+ offset,function(data){
            $('#lastPostLoader').hide();
            if (data != "") {
              $(".offer:last").after(data);
              $(".offer").trigger( "create" );
              $(".offer").trigger('updatelayout');
              get_more_when_can_not_scroll();
            }

          });
        }
        else
          flag_scroll = 1;

      }
      get_more_when_can_not_scroll();
      $(window).scroll(function(){
        if (flag_scroll == 1){
          var h_document = $(document).height();
          var wall = h_document - 100;
          var h_window = $(window).height();
          if  ($(window).scrollTop() >= ( wall -  h_window)){
            var $this = $(this), handler = arguments.callee;
            $this.unbind('scroll', handler)
            var offset = $(".offer:last").attr("data-offset");
            $('#lastPostLoader').show();
            $.get("/offers/get_more_offers?offset="+ offset,function(data){
              $('#lastPostLoader').hide();
              if (data != "") {
                $(".offer:last").after(data);
                $(".offer").trigger( "create" );
                $(".offer").trigger('updatelayout');
                $this.scroll(handler);
              }
            });
          }
        }
      });

    });

  </script>
<% end %>

app/views/offers/index.mobile_backup.erb
<div data-role='page' data-url="<%= offers_path %>">
  <div data-role="header" data-theme="e" data-position="fixed">
    <h1>Deekau</h1>
  </div>
  <div class="m_width m_text_right m_min_width m_text_center">
    <div data-role='content' >
      <%= render "shared/session_user" %>
      <br /><br />
      <% if current_user and current_user.merchant == nil %>
        <%= link_to "You are Merchant?",new_merchant_path ,'data-role'=>'button','data-theme'=>'i'%>
      <% elsif current_user and current_user.merchant  %>
        <%= link_to "My Merchant",current_user.merchant ,'data-role'=>'button'%>
      <% end %>
      <% if current_user and current_user.merchant != nil %>
        <%= link_to 'New offer', new_offer_path , 'data-role'=>'button' ,'data-theme'=>'c'%>
      <% end %>
      <br style="clear:both;" />
      <br style="clear:both;" />
      <% #if current_user and current_user.merchant != nil %>
        <ul data-role="listview"  data-inset="true" data-divider-theme="b">
          <li data-role="list-divider" data-divider-theme="b" >Offers</li>
            <% @offers.each_with_index do |offer,offset| %>
            <li data-offset="<%= offset + 1 %>" class="offer">
              <a href="<%= offer_path(offer)%>">
                <h3><%=  offer.name %></h3>
                <p><%=  offer.description %></p>
              </a>
              <%= link_to 'Destroy', offer, confirm: 'Are you sure?', method: :delete ,'data-icon'=>'delete'%>
              <div data-role="controlgroup" data-type="horizontal">
                <%= link_to 'Edit', edit_offer_path(offer) ,'data-role'=>'button' %>
                <a href="#" data-role="none" title="share on facebook"><img class='author-image-button' src="assets/mobile/facebook.png" /></a>
                <a href="#" data-role="none" title="share on twiter"><img class='author-image-button' src="assets/mobile/twitter.png" /></a>
                <a href="#" data-role="none" title="add to google+"><img class='author-image-button' src="assets/mobile/google.png" /></a>
              </div>
            </li>
          <% end %>
        </ul>
        <br />
        <br />
      <% #end %>
      
    </div>
  </div>
  <div data-role='footer'>

  </div>
</div>


<%= content_for :jsScript do %>
<script type="text/javascript">
  $(document).bind('pageinit',function(){
$('#lastPostLoader').hide();

      $(window).scroll(function(){
        var h_document = $(document).height();
        var wall = h_document - 100;
        var h_window = $(window).height();
        if  ($(window).scrollTop() >= ( wall -  h_window)){
          var $this = $(this), handler = arguments.callee;
          $this.unbind('scroll', handler)
          var offset = $(".offer:last").attr("data-offset");
          $('#lastPostLoader').show();
          $.get("/offers/get_more_offers?offset="+ offset,function(data){
            $('#lastPostLoader').hide();
            if (data != "") {
              $(".offer:last").after(data);
              $(".offer").trigger( "create" );
              $(".offer").trigger('updatelayout');
              $this.scroll(handler);
            }
          });
        }
      });
  });

  </script>
<% end %>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/new.mobile.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag "mobile/offer.css" %>
  <%#= javascript_include_tag 'jquery/jquery-ui-1.8.18.custom.min' %>
  <%= javascript_include_tag "desktop/validate_offer.js" %>
<% end %>
<script type='text/javascript'>
  $("#offer_new").bind("mobileinit", function(){
    <%#*console.log("asdas");%>
    alert("laskdlksal");
    $.mobile.page.prototype.options.keepNative = "input[type='checkbox']";
     
  });
</script>

<div id="offer_new" data-role="page" data-them="deekau" data-url="<%=  %>">
  <div data-role="header" data-theme="deekau">
    <div id="header">
      <div id="logo">
        <%=  link_to (image_tag("logo.png",:style => "height: 29px;")) %>
      </div>
      <div id="box_login" style="padding-top: 5px;">
        <a href="/user/login" class="ui-link">Sign in</a>
      </div>
    </div>
    <div id="back_bar">
      <a data-rel="back" data-direction="reverse" class="link-back" href="#" style="color: #ffffff; font-weight: bold; font-size: 13px;">
        <span class="arrow"></span>Back
      </a>
    </div>
  </div>
  <div data-role="content" >
    <h2 class="heading"> <%=  t("offers.new.title")%></h2>
    <%= render 'form' %>
  </div>
  <div data-role="footer" data-theme="deekau-footer">
    <div id="footer"></div>
  </div>
</div>

app/views/offers/show.mobile.erb
<div data-role='page' data-url="<%= merchant_offer_path(@offer) %>">
<%= render 'image/form_upload' ,:object => @offer %>
    <h1>Deekau</h1>
  </div>
  <div class="m_width m_text_center m_min_width">
    <div data-role='content' >
      <p id="notice"><%= notice %></p>

      <p>
        <b>Name: </b>
        <%= @offer.name %>
      </p>

      <p>
        <b>Description:</b>
        <%= @offer.description %>
      </p>


      <%= link_to 'Edit', edit_merchant_offer_path(@offer) %> |
      <%= link_to 'Back', merchant_offers_path %>

    </div>
  </div>
  <div data-role='footer'>

  </div>
</div>

app/views/offers/tmp_list.mobile.erb
<div data-role="page" data-them="deekau">
  <div data-role="header" data-theme="deekau">
    <div id="header">
      <div id="logo">
        <%=  link_to (image_tag("logo.png",:style => "height: 29px;")) %>
      </div>
      <div id="box_login" style="padding-top: 5px;">
        <a href="/user/login" class="ui-link">Sign in</a>
      </div>
    </div>
    <div id="back_bar">
      <a data-rel="back" data-direction="reverse" class="link-back" href="#" style="color: #ffffff; font-weight: bold; font-size: 13px;">
        <span class="arrow"></span>Back
      </a>
    </div>
  </div>
  <div data-role="content" >
    <div id="content">
      <ul class="offer_list" data-role="listview">
        <li>
          <div class="offer_box">
            <%= link_to(image_tag("THUMB_01.jpg"),"#",:class => "img_box lfloat")%>
            <div class="offer_detail" >
              <div class="offer_title">
                Bright Mezzanine Studio
              </div>
              <p class="lfloat">A second bedroom again with A second bedroom again with A second bedroom again with A second bedroom again with</p>
            </div>
            <div class="rfloat" style="width: 20px; height: 100%; display: block; margin-top: -10px;">
              <a class="link-next" href="/"><span class="arrow_icon"></span></a>
            </div>
          </div>
        </li>
        <li>
          <div class="offer_box">
            <%= link_to(image_tag("THUMB_01.jpg"),"#",:class => "img_box lfloat")%>
            <div class="offer_detail" >
              <div class="offer_title">
                Bright Mezzanine Studio
              </div>
              <p class="lfloat">A second bedroom again with A second bedroom again with A second bedroom again with A second bedroom again with</p>
            </div>
            <div class="rfloat" style="width: 20px; height: 100%; display: block; margin-top: -10px;">
              <a class="link-next" href="/"><span class="arrow_icon"></span></a>
            </div>
          </div>
          </li>
      </ul>
    </div>
  </div>
  <div data-role="footer" data-theme="deekau-footer">
    <div id="footer"></div>
  </div>
</div>