config/routes.rb
Company::Application.routes.draw do

  resources :photos, :only => [:index, :show, :new, :create] do
    post 'upload', :on => :collection
  end

  match "/albums" => "albums#index"
  match "/social_post" => "home#social_post"
  post "users/unique_email"
  get "home/" => "home#index"
  get "home/lookup_address" =>"home#lookup_address"
  get 'home/autocomplete'
  get 'home/autocomplete_category'
  get 'home/get_current_position' => 'home#get_current_position' ,:as => :get_current_position
  get 'offers/tmp_list' , :as => :offers_list
  get "/users/get_user"
  get '/list_offers' => "offers#list_offer" , :as => :list_offers
  get 'merchats/tmp_detail'
  get 'offers/tmp_filter'
  get '/categories/top_lvl'
  get '/merchants/get_offers_quota'
  match 'categories/:category' => "categories#category"
  match 'categories/:category/offers' => "categories#offers"
  match 'categories/:category/:sub_category' => "categories#sub_category"
  match 'categories/:category/:sub_category/offers' => "categories#offers"
  
  resources :articles
  resources :countries do
    resources :cities
  end

  
  match '/users/profile' => 'users#show' ,:as => :user_profile
  match '/merchants/get_image' => 'merchants#get_image' ,:as => :merchant_get_image
  match '/offers/get_image' => 'offers#get_image' ,:as => :offer_get_image

  match "offers/:id/get_images" => "offers#get_image"
  post 'offers/create/:id'  => "offers#create"
  
  match "/images/:id/delete" => "images#destroy" ,:as => :delete_image
  match "/merchant_images/:id/delete" => "merchant_images#destroy" ,:as => :delete_merchant_image
  match "/offer_images/:id/delete" => "offer_images#destroy" ,:as => :delete_offer_image
  match 'offers/new' => 'offers#new'
  match '/offers' => 'offers#index'
  get 'offers/create/:id'  => "offers#get_offer"

  devise_for :users, :controllers => { :registrations => "registrations",:omniauth_callbacks => "omniauth_callbacks",:sessions => "sessions" }
  match "/offers/get_more_offers" => "offers#get_more_offers"
  
  resources :merchant_types
  resources :merchants do
    collection do
      get 'set_favourite'
    end
    resources :offers do 
      collection do
        get 'set_favourite'
      end
    end
  end

  match '/users/profile/users/update' =>  'users#update'
  match '/users/update' =>  'users#update'
  match '/users/friends' => 'users#friends'
  match '/users/find_friend_oauth_provider' => 'users#find_friend_oauth_provider'
  match '/users/friend_action' => 'users#friend_action'
  match '/users/invite' => 'users#invite'

  match '/chats/find/:id' => 'chats#find'
  match '/chats/load_more' => 'chats#load_more'
  match '/chats/init' => 'chats#init'
  match '/chats/add_recent_chat' => 'chats#add_recent_chat'

  post '/get_google_places'  => "offers#get_google_places"

  
  root :to =>'home#index'

end

app/models/country.rb
require 'mongoid'

class Country
  include Mongoid::Document
  embeds_many :cities
#  field :name,    :type => String
  field :code,    :type => String
  field :iso_code_two_letter, :type => String
  field :iso_code_three_letter, :type => String
  field :iso_number, :type => Integer
  field :continent, :type => String
  
  field :created_at,    :type => DateTime, :default => DateTime.current
  field :updated_at,    :type => DateTime, :default => DateTime.current
  field :_id,:type => String
#  validates_presence_of :name
#  validates_presence_of :code
#  validates_uniqueness_of :name
#  validates_uniqueness_of :code

  def find_by_name(input)
    return Country.where("name = #{input}").first
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.paginate(:page => params[:page],:per_page => 10)
#    Post.paginate(:page => params[:page], :per_page => 30)
    respond_to do |format|
      format.html # index.html.erbb
      format.json { render json: @countries }
    end
  end

  def show
    @country = Country.find(params[:id])
    @cities = @country.cities.paginate(:page => params[:page],:per_page => 2)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @country }
    end
  end


  def new
    @country = Country.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @country }
    end
  end


  def edit
    @country = Country.find(params[:id])
  end



  def create
    @country = Country.new(params[:country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render json: @country, status: :created, location: @country }
      else
        format.html { render action: "new" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @country = Country.find(params[:id])

    respond_to do |format|
      if @country.update_attributes(params[:article])
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @country = Country.find(params[:id])
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end
end

app/views/countries/_new_form.html.erb
<div class="modal fade" id="newCountry" >
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>New country</h3>
  </div>
  <%= form_for(@country = Country.new) do |f| %>
    <div class="modal-body">
      <% if @country.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

          <ul>
            <% @country.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="control-group">
        <%= f.label :name %><br />
        <%= f.text_field :name,:class => 'validate' %>
        <span class="country_name help-inline"></span>
      </div>
      <div class="control-group">
        <%= f.label :code %><br />
        <%= f.text_field :code,:class => 'validate'  %>
        <span class="country_code help-inline"></span>
      </div>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      <input type="submit" id="submit" value="Submit" class="btn btn-primary" />
    </div>
  <% end %>



</div>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<%= javascript_include_tag "validate_form.js" %>
<%=  content_for :jsScript do %>
  <script type="text/javascript">
    $(document).bind("mobileinit", function(){

      //$.mobile.autoInitialize = false;
          
    });
    $(document).bind('pageinit',function(){
      $('#newCountry').modal('hide');

    });
  </script>
<% end %>
<h1>Listing countries</h1>
<a class="btn" data-toggle="modal" data-target="#newCountry" >New Country</a>

<table>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @countries.each do |country| %>
    <tr>
      <td><%= country.name %></td>
      <td><%= country.code %></td>
      <td><%= link_to 'Show', country %> |</td>
      <td><%= link_to 'Edit', edit_country_path(country) %> | </td>
      <td><%= link_to 'Destroy', country, confirm: 'Are you sure?', method: :delete %> </td>
    </tr>
  <% end %>
</table>

<br />
<%= will_paginate @countries , 'data-role'=>'none' ,'data-cache-dom' => false %>

<%= render 'countries/new_form' %>

app/views/countries/show.html.erb
<%= javascript_include_tag "validate_form.js" %>
<%=  content_for :jsScript do %>
  <script type="text/javascript">
    $(document).bind("mobileinit", function(){

      //$.mobile.autoInitialize = false;

    });
    $(document).bind('pageinit',function(){
      $('#newCity').modal('hide');

    });
  </script>
<% end %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @country.name %>
</p>

<p>
  <b>Code:</b>
  <%= @country.code %>
</p>


<h1>Listing cities</h1>
<a class="btn" data-toggle="modal" data-target="#newCity" >New City</a>
<%= link_to 'Back to Countries', countries_path %>
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Slug</th>
    <th>State</th>
    <th>Lat</th>
    <th>Lon</th>
    <th>Timezone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%= city.name %></td>
    <td><%= city.slug %></td>
    <td><%= city.state %></td>
    <td><%= city.lat %></td>
    <td><%= city.lon %></td>
    <td><%= city.timezone %></td>
    <td><%= link_to 'Show', country_city_path(@country.id,city.id) %></td>
    <td><%= link_to 'Edit', edit_country_city_path(@country.id,city.id) %></td>
    <td><%= link_to 'Destroy', country_city_path(@country.id,city.id), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @cities , 'data-role'=>'none' ,'data-cache-dom' => false %>
<%= render 'cities/new_form' %>