config/routes.rb
Company::Application.routes.draw do

  resources :photos, :only => [:index, :show, :new, :create] do
    post 'upload', :on => :collection
  end

  match "/albums" => "albums#index"
  match "/social_post" => "home#social_post"
  post "users/unique_email"
  get "home/" => "home#index"
  get "home/lookup_address" =>"home#lookup_address"
  get 'home/autocomplete'
  get 'home/autocomplete_category'
  get 'home/get_current_position' => 'home#get_current_position' ,:as => :get_current_position
  get 'offers/tmp_list' , :as => :offers_list
  get "/users/get_user"
  get '/list_offers' => "offers#list_offer" , :as => :list_offers
  get 'merchats/tmp_detail'
  get 'offers/tmp_filter'
  get '/categories/top_lvl'
  get '/merchants/get_offers_quota'
  match 'categories/:category' => "categories#category"
  match 'categories/:category/offers' => "categories#offers"
  match 'categories/:category/:sub_category' => "categories#sub_category"
  match 'categories/:category/:sub_category/offers' => "categories#offers"
  
  resources :articles
  resources :countries do
    resources :cities
  end

  
  match '/users/profile' => 'users#show' ,:as => :user_profile
  match '/merchants/get_image' => 'merchants#get_image' ,:as => :merchant_get_image
  match '/offers/get_image' => 'offers#get_image' ,:as => :offer_get_image

  match "offers/:id/get_images" => "offers#get_image"
  post 'offers/create/:id'  => "offers#create"
  
  match "/images/:id/delete" => "images#destroy" ,:as => :delete_image
  match "/merchant_images/:id/delete" => "merchant_images#destroy" ,:as => :delete_merchant_image
  match "/offer_images/:id/delete" => "offer_images#destroy" ,:as => :delete_offer_image
  match 'offers/new' => 'offers#new'
  match '/offers' => 'offers#index'
  get 'offers/create/:id'  => "offers#get_offer"

  devise_for :users, :controllers => { :registrations => "registrations",:omniauth_callbacks => "omniauth_callbacks",:sessions => "sessions" }
  match "/offers/get_more_offers" => "offers#get_more_offers"
  
  resources :merchant_types
  resources :merchants do
    collection do
      get 'set_favourite'
    end
    resources :offers do 
      collection do
        get 'set_favourite'
      end
    end
  end

  match '/users/profile/users/update' =>  'users#update'
  match '/users/update' =>  'users#update'
  match '/users/friends' => 'users#friends'
  match '/users/find_friend_oauth_provider' => 'users#find_friend_oauth_provider'
  match '/users/friend_action' => 'users#friend_action'
  match '/users/invite' => 'users#invite'

  match '/chats/find/:id' => 'chats#find'
  match '/chats/load_more' => 'chats#load_more'
  match '/chats/init' => 'chats#init'
  match '/chats/add_recent_chat' => 'chats#add_recent_chat'

  post '/get_google_places'  => "offers#get_google_places"

  
  root :to =>'home#index'

end

app/models/city.rb
require 'active_support'
require 'mongoid'

class City
  include Mongoid::Document
  #has_many :offers
  #  embedded_in :country
  field :_id, :type => String
  field :geonames_id, :type => Integer
  # field :country_id,    :type => String
  field :name,    :type => String
  field :ascii_name, :type => String
  field :alternate_name,:type =>  String
  field :slug,    :type => String
  field :state,    :type => String
  field :latitude , :type => BigDecimal
  field :longitude, :type => BigDecimal
  # field :country_iso_code_two_letters, :type => String
  field :geonames_timezone_id,:type => Integer
  field :timezone,    :type => String
  field :country_tag, :type => String
  #  validates_presence_of :name
  #  validates_presence_of :slug
  #  validates_presence_of :lat
  #  validates_presence_of :lon
  #  validates_uniqueness_of :slug

  
  def self.find_by_name(input)
    return City.where("name = '"+"#{input}"+"'").first
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  load_and_authorize_resource

  # GET /cities
  # GET /cities.json
  def index
    @country = Country.find(params[:country_id])
    @cities = @country.cities

    respond_to do |format|
      format.html # index.html.erbb
      format.json { render json: @cities }
    end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @country = Country.find(params[:country_id])
    @city = City.find("#{params[:id]}")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/new
  # GET /cities/new.json
  def new
    @country = Country.find(params[:country_id])
    @city = @country.cities.build 
    puts @city.to_json
    respond_to do |format|
      format.html # new.html.erb
      
    end
  end

  # GET /cities/1/edit
  def edit
    @country = Country.find(params[:country_id])
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.json
  def create
    @country = Country.find(params[:country_id])
    @city = City.new(params[:city])

    respond_to do |format|
      if @city.save
        format.html { redirect_to @country, notice: 'City was successfully created.' }
        format.json { render json: @city, status: :created, location: @city }
      else
        format.html { render action: "new" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cities/1
  # PUT /cities/1.json
  def update
    @country = Country.find(params[:country_id])
    @city = City.find(params[:id])

    respond_to do |format|
      if @city.update_attributes(params[:city])
        format.html { redirect_to @country, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @country = Country.find(params[:country_id])
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html { redirect_to @country }
      format.json { head :no_content }
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_new_form.html.erb
<div class="modal fade" id="newCity" >
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>New city</h3>
  </div>
  <%= form_for([@country,@city = @country.cities.build]) do |f| %>
    <div class="modal-body">
      <% if @city.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>
          <ul>
            <% @city.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="control-group">
        <%= f.label :name %>
        <%= f.text_field :name ,:class => 'validate'%>
        <span class="city_name help-inline"></span>
      </div>


      <div class="control-group">
        <%= f.label :slug %><br />
        <%= f.text_field :slug ,:class => 'validate' %>
        <span class="city_slug help-inline"></span>
      </div>

      <div class="control-group">
        <%= f.label :state %><br />
        <%= f.text_field :state %>
      </div>

      <div class="control-group">
        <%= f.label :lon %><br />
        <%= f.text_field :lon,:class => 'validate' %>
        <span class="city_lon help-inline"></span>
      </div>

      <div class="control-group">
        <%= f.label :lat %><br />
        <%= f.text_field :lat,:class => 'validate' %>
        <span class="city_lat help-inline"></span>
      </div>


      <div class="control-group">
        <%= f.label :country %><br />
        <%= f.select :country_id, options_from_collection_for_select( Country.all(), "id", "name") ,'data-role'=>'none' %>
      </div>

      <div class="control-group">
        <%= f.label :timezone %><br />
        <%= f.text_field :timezone %>
      </div>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      <input type="submit" id="submit" value="Submit" class="btn btn-primary" />
    </div>

  <% end %>
</div>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Back', country_path(@country) %>

app/views/cities/index.html.erb
<%= javascript_include_tag "validate_form.js" %>
<%=  content_for :jsScript do %>
  <script type="text/javascript">
    $(document).bind("mobileinit", function(){

      //$.mobile.autoInitialize = false;

    });
    $(document).bind('pageinit',function(){
      $('#newCity').modal('hide');

    });
  </script>
<% end %>

<h1>Listing cities</h1>
<a class="btn" data-toggle="modal" data-target="#newCity" >New City</a>
<%= render 'cities/new_form' %>
<table>
  <tr>
    <th>Name</th>
    <th>Slug</th>
    <th>State</th>
    <th>Country</th>
    <th>Lon</th>
    <th>Lat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%= city.name %></td>
    <td><%= city.slug %></td>
    <td><%= city.state %></td>
    <td><%= city.country ? city.country.name : '' %> </td>
    <td><%= city.lon %></td>
    <td><%= city.lat %></td>
    <td><%= link_to 'Show', city %></td>
    <td><%= link_to 'Edit', edit_city_path(city) %></td>
    <td><%= link_to 'Destroy', city, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<%= javascript_include_tag "validate_form.js" %>
<%= content_for :jsScript do %>
 
<script type="text/javascript">
  $(document).bind('pageinit',function(){

  });
</script>
<% end %>
<script type="text/javascript">

</script>
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', country_path(@country) %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @city.name %>
</p>

<p>
  <b>Slug:</b>
  <%= @city.slug %>
</p>

<p>
  <b>State:</b>
  <%= @city.state %>
</p>
<p>
  <b>Country:</b>
  <%= @city.country ? @city.country.name : '' %>
</p>
<p>
  <b>Lon:</b>
  <%= @city.lon %>
</p>

<p>
  <b>Lat:</b>
  <%= @city.lat %>
</p>
<p>
  <b>Time zone:</b>
  <%= @city.timezone %>
</p>

<%= link_to 'Edit', edit_country_city_path(@country.id,@city.id) %> |
<%= link_to 'Back', country_path(@country) %>